# Generated by Django 6.0.6 on 2026-06-20 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('restaurante', 'Restaurante'), ('piscina', 'Piscina'), ('salon-eventos', 'Salón de Eventos')], max_length=20, unique=True, verbose_name='Identificador')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Hora fin'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reservations.zone', verbose_name='Zona'),
        ),
    ]
