# Generated by Django 6.0.6 on 2026-06-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('confirmed', 'Confirmación'), ('cancelled', 'Cancelación')], max_length=20, unique=True, verbose_name='Tipo')),
                ('subject', models.CharField(default='Tu reserva en Restaurante El Lago', max_length=200, verbose_name='Asunto')),
                ('body_text', models.TextField(verbose_name='Cuerpo (texto plano)')),
                ('body_html', models.TextField(verbose_name='Cuerpo (HTML)')),
            ],
            options={
                'verbose_name': 'Plantilla de mensaje',
                'verbose_name_plural': 'Plantillas de mensaje',
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('max_capacity', models.PositiveSmallIntegerField(default=20, verbose_name='Capacidad máxima')),
            ],
            options={
                'verbose_name': 'Franja de disponibilidad',
                'verbose_name_plural': 'Franjas de disponibilidad',
                'ordering': ['day_of_week', 'time'],
                'unique_together': {('day_of_week', 'time')},
            },
        ),
    ]
