# Generated by Django 6.0.6 on 2026-06-20 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailabilitySlot',
        ),
    ]
